version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: HadesGod
      POSTGRES_DB: graphql_db
    ports:
      - 5432:5432

